apiVersion: v1
kind: Service
metadata:
  name: server-ext-connection
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      name: gateway
      nodePort: 30000
    - protocol: TCP
      port: 9082
      targetPort: 9082
      name: gatewy-grpc
      nodePort: 30001

  selector:
    app: server